### ISSUE TITLE
Error intializing Java : System.NullReferenceException: Java initialization timeout expired.

### ISSUE THREAD

**Issue by prolifel** [UiPath/Script.Activities#183]
**Detail**
I executed the [demo](https://docs.uipath.com/activities/docs/running-static-and-object-methods) from UiPath Studio Docs and it works fine.
Then, i create my own sequence like this:

![image](https://user-images.githubusercontent.com/61197343/135595095-0234bf0b-101c-4b4f-a4d5-c50dc0e9a691.png)

UiPath.Java.Activities.JavaScope input properties are using default value.
**Using UiPath.Java.Activities version 1.3.1.**

Then, it gets me error like this:
![image](https://user-images.githubusercontent.com/61197343/135595584-09ffa65c-b71b-4277-b75a-1c00869e8c4e.png)

```
Java Scope: Error intializing Java : System.NullReferenceException: Java initialization timeout expired.
   at UiPath.Java.Service.JavaService.<StartServiceAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Java.JavaInvoker.<StartJavaService>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Java.Activities.JavaScope.<ExecuteAsync>d__16.MoveNext()
```

So, i set `Init timeout` to 30000ms and still get the same error. I try another timeout limit and it errors too.

Then, i copy the `Java Scope` activity from UiPath Docs example, and i get the same error too. 

I try to downgrade **UiPath.Java.Activities to 1.0.6863.33114** (it is same like the example from UiPath Docs), and i got this message:

```
21.4.4+Branch.master.Sha.a8b5101efe02651274064093e9c7410fedff7696

Source: Java Scope

Message: Error intializing Java : System.NullReferenceException: Object reference not set to an instance of an object.
   at UiPath.Java.Service.JavaService.<StartServiceAsync>b__7_2(IAsyncResult ar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Java.Service.JavaService.<StartServiceAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Java.JavaInvoker.<StartJavaService>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Java.Activities.JavaScope.<ExecuteAsync>d__12.MoveNext()

Exception Type: System.InvalidOperationException

RemoteException wrapping System.InvalidOperationException: Error intializing Java : System.NullReferenceException: Object reference not set to an instance of an object.
   at UiPath.Java.Service.JavaService.<StartServiceAsync>b__7_2(IAsyncResult ar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Java.Service.JavaService.<StartServiceAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Java.JavaInvoker.<StartJavaService>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Java.Activities.JavaScope.<ExecuteAsync>d__12.MoveNext() 
   at UiPath.Shared.Activities.AsyncTaskNativeImplementation.BookmarkResumptionCallback(NativeActivityContext context, Object value)
   at UiPath.Shared.Activities.AsyncTaskNativeActivity.BookmarkResumptionCallback(NativeActivityContext context, Bookmark bookmark, Object value)
   at System.Activities.Runtime.BookmarkCallbackWrapper.Invoke(NativeActivityContext context, Bookmark bookmark, Object value)
   at System.Activities.Runtime.BookmarkWorkItem.Execute(ActivityExecutor executor, BookmarkManager bookmarkManager)
```

I've set my path environment to `C:\Program Files\Java\jdk-11.0.12\bin`
![image](https://user-images.githubusercontent.com/61197343/135597845-1f222564-844b-4ddf-87c2-33774c394364.png)

Could anybody help me?

The weird part is i always success to run the example robot from UiPath docs.
Any solution could help. Thanks!

**Comment by petcua1** [comment]
Can you please provide the project that you are trying to run?

Regards,

Alex

**Comment by prolifel** [comment]
Its already done @petcua1

sorry for not close this thread
